version: '3.2'
services:
  app:
    build:
      context: .
    command: python3 /usr/src/app/app.py
    volumes:
      - ./src:/usr/src/app
      - ./service-account.json:/tmp/service-account.json
    environment: 
      PORT: 3000
      TABLE_ID_RAW: "data_gov_au.australian_insolvencies_raw"
      TABLE_ID: "data_gov_au.australian_insolvencies"
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json
      LOAD_KEY: abc123
      URL: http://localhost:3000
    ports:
      - 3000:3000
    restart: always